### ISSUE TITLE
disabling ANDROID_PARANOID_NETWORK breaks it

### ISSUE THREAD

**Issue by amery** [linux-sunxi/linux-sunxi#7]
disabling ANDROID_PARANOID_NETWORK leads to:

```
security/commoncap.c: In function 'cap_capable':
security/commoncap.c:90:40: error: 'AID_NET_RAW' undeclared (first use in this function)
security/commoncap.c:90:40: note: each undeclared identifier is reported only once for each function it appears in
security/commoncap.c:92:42: error: 'AID_NET_ADMIN' undeclared (first use in this function)
make[1]: *** [security/commoncap.o] Error 1
```

**Comment by amery** [comment]
bug introduced in 622495a5adf75911922749bb10ba7b1b8c6b8639 and now fixed in 7041266a29e9681fc13034f345cdcc269d672f83
